### ISSUE TITLE
Create SessionFactory

### ISSUE THREAD

**Issue by ifkin** [Demonlord32/AT-Consulting#12]
Быть может как-то можно чекать, есть ли у нас уже созданная SessionFactory?
И не создавать ее при каждом обращении с клиента.

**Comment by Demonlord32** [comment]
Я решил проблему двойного создания экземпляра SessionFactory. Кстати, в SO не рекомендуют юзать одну сессию в webapp'е: https://stackoverflow.com/questions/8046662/hibernate-opensession-vs-getcurrentsession

**Comment by ifkin** [comment]
Это факт!

Тут очень тонкий нюанс, требующий глубокого аналайза (как пафосно то звучит).

У нас есть SessionFactor и Session.

Этот тонкий нюанс пролегает там, где мы решаем примерно следующие задачи:

- Можно и нужно ли создавать несколько SessionFactor?
- Создавать Session при обращении клиента? Или сразу создавать несколько сессий а уже внутри них что-то делать? (т.е. заранее иметь заготовку)
- Если мы создаем Session заранее то сколько их создать?
