### ISSUE TITLE
Iterator в DatabaseHelper

### ISSUE THREAD

**Issue by ifkin** [Demonlord32/AT-Consulting#14]
Зачем нам Iterator в checkUser?

Мб просто проверять размер выборки? Если он == 0 делаем вывод, что логин / пасс кривые.

В противном случае лог / пасс - найдены в бд.

Кстати, стоит учесть что размер выборки может иметь только два состояния: 0 и 1 :)

**Comment by Demonlord32** [comment]
Удалил цикл. Но итератор оставил для того, чтобы извлечь имя и фамилию для вывода надписи типа "name" + "family" добро пожаловать.

**Comment by ifkin** [comment]
catch (NoSuchElementException e){
            return "Простите, но ваш логин или пароль введён неверно. Пожалуйста, введите снова пароль и логин";
        }

Я не согласен вот с этой вещью.

catch подразумевает обработку какой-либо серверной ошибки.

В нашем случае неверный логин / пасс - это не ошибка.

А сейчас, судя по всему, когда мы вводим неверные лог/пасс - у нас сценарий идет в catch. Так нельзя.

**Comment by ifkin** [comment]
Что думаешь по поводу проверки размера вот этой вещи

List usersList = query.list();

**Comment by Demonlord32** [comment]
Исправил. Убрал отлов этого исключения и теперь проверяю просто размер выборки.

**Comment by ifkin** [comment]
ok
