### ISSUE TITLE
double soap:Body

### ISSUE THREAD

**Issue by ifkin** [Demonlord32/AT-Consulting#5]
Давай, все-таки, избавимся от генерации двух блоков body

**Comment by ifkin** [comment]
Не исправлено.

В плюс то, что ты это вытащил в отдельный метод (читается гораздо удобнее).

Однако body все равно создается дважды.

**Comment by Demonlord32** [comment]
Без удаления и создания не получается. Потому что у Element нету методов для перемещения внутренних Element'ов. Другого пути я не знаю. Только что просмотрел список методов к Element.

**Comment by Demonlord32** [comment]
Решил без удаления и создания.

**Comment by ifkin** [comment]
good
