### ISSUE TITLE
login port

### ISSUE THREAD

**Issue by ifkin** [Demonlord32/AT-Consulting#7]
Я нахожусь на странице http://127.0.0.1/JEETest/html/index.html

Ввожу логин / пасс > клацаю "Touch me" > Кидается post на http://127.0.0.1:8080/JEETest/login > aborted

nb! данный баг блокирет проверку Критерия №6 (Hibernate)

**Comment by Demonlord32** [comment]
Не могу воспроизвести баг
![image](https://cloud.githubusercontent.com/assets/10107735/12015410/8192c6b8-ad6e-11e5-8a77-98e6cc3d9e03.png)

**Comment by ifkin** [comment]
ok!
